" TODO wat do
set nocompatible

" TODO Merge Maloy's file into files in this directory (can add additional
" ones)
source $HOME/.vim/rc/general.vim
source $HOME/.vim/rc/mappings.vim
source $HOME/.vim/rc/plugins.vim
source $HOME/.vim/rc/ui.vim
